PREFIX xsd:		<http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:		<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:		<http://www.w3.org/2002/07/owl#>
PREFIX pav:		<http://purl.org/pav/>
PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>
PREFIX prov:	<http://www.w3.org/ns/prov#>
PREFIX lis:		<http://standards.iso.org/iso/15926/part14/>
PREFIX tpl:		<https://ottr.xyz/lib/eng/mel/>
PREFIX upp:		<http://data.aibel.com/asset/equinor/AskjaUPP/>
PREFIX pca:		<http://data.posccaesar.org/rdl/>
PREFIX ottr:	<http://ns.ottr.xyz/0.4/>

SELECT *
WHERE {
  [] ottr:of tpl:CentrifugalPumpSkid ;
     ottr:values/rdf:first ?tag_number ;
     ottr:values/rdf:rest/rdf:first ?pca_type ;
     ottr:values/rdf:rest/rdf:rest/rdf:first ?pressure_1_barg ;
  .
}